FROM python:3.8-alpine

RUN mkdir -p /app
WORKDIR /app

COPY src/requirements.txt /app

RUN apk add pkgconfig gcc fuse3 fuse3-dev linux-headers musl-dev
RUN pip install -r /app/requirements.txt

COPY src/ /app

CMD ["python", "main.py"]
