version: '3.4'

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      IMAP_USER: 'foo'
      IMAP_PASS: 'bar'
      IMAP_HOST: 'imap.fastmail.com'
      MSG_LIMIT: 20
      REFRESH_INTERVAL: 30
      LOGURU_LEVEL: TRACE
    # mounting a new FS seems to be not possible
    # without SYS_ADMIN cap, but it doesn't work
    # even with ALL caps, instead it requires
    # privileged? (investigate)
    # cap_add:
    #   - SYS_ADMIN
    privileged: true
    devices:
      - '/dev/fuse'
